version: '2'

services:
  nginx:
    container_name: nginx
    build: ./dockerfiles/nginx
    image: nginx-image
    ports:
      - "80:80"
      - "443:443"
    restart: always

  site01-db-data:
    container_name: site01-db-data
    build: ./dockerfiles/site-01/vol-db
    image: site01-db-data-image
    restart: never

  site01-db:
    container_name: site01-db
    build: ./dockerfiles/site-01/db
    image: site01-db-image
    restart: always
    volumes:
      - site01-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  site01-wp-data:
    container_name: site01-wp-data
    build: ./dockerfiles/site-01/vol-wp
    image: site01-wp-data-image
    restart: never

  site01-wp:
    container_name: site01-wp
    build: ./dockerfiles/site-01/wp
    image: site01-wp-image
    restart: always
    depends_on:
      - site01-db
    links:
      - site01-db
    volumes:
      - site01-wp-data:/var/www/html
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: site01-db:3306
      WORDPRESS_DB_PASSWORD: wordpress

#  site02-db-data:
#    container_name: site02-db-data
#    build: ./dockerfiles/site-02/vol-db
#    image: site02-db-data-image
#    restart: never

#  site02-db:
#    container_name: site02-db
#    build: ./dockerfiles/site-02/db
#    image: site02-db-image
#    restart: always
#    networks:
#      back:
#        ipv4_address: 172.16.238.212
#    volumes:
#      - site02-db-data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: wordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress

#  site02-wp-data:
#    container_name: site02-wp-data
#    build: ./dockerfiles/site-02/vol-wp
#    image: site02-wp-data-image
#    restart: never

#  site02-wp:
#    container_name: site02-wp
#    build: ./dockerfiles/site-02/wp
#    image: site02-wp-image
#    restart: always
#    networks:
#      back:
#        ipv4_address: 172.16.238.202
#      front:
#        ipv4_address: 172.16.238.102
#    depends_on:
#      - site02-db
#    volumes:
#      - site02-wp-data:/var/www/html
#    ports:
#      - "8000:80"
#    environment:
#      WORDPRESS_DB_HOST: http://172.16.238.212:3306
#      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  site01-db-data:
    external: false
  site01-wp-data:
    external: false
#  site02-db-data:
#    external: false
#  site02-wp-data:
#    external: false

# networks:
#   front:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - 
#           subnet: 172.16.238.100/24
#           gateway: 172.16.238.120
#   back:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - 
#           subnet: 172.16.238.200/24
#           gateway: 172.16.238.220
